version: '3'
services:
  postgres_support:
    image: postgres:15-alpine
    container_name: postgres_support
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  zookeeper_support:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper_support
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  broker_support:
    image: confluentinc/cp-kafka:7.0.1
    container_name: broker_support
    ports:
      # To learn about configuring Kafka for access across networks see
      # https://www.confluent.io/blog/kafka-client-cannot-connect-to-broker-on-aws-on-docker-etc/
      - "9092:9092"
    depends_on:
      - zookeeper_support
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper_support:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker_support:9092,PLAINTEXT_INTERNAL://broker_support:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
  support:
    build:
      context: .
    container_name: support
    ports:
      - "8080:8080"
    depends_on:
      - broker_support
      - postgres_support
    environment:
      DATABASE_URL: "jdbc:postgresql://postgres_support:5432/"
      DATABASE_USERNAME: "postgres"
      DATABASE_PASSWORD: "postgres"
      KAFKA_GROUP_ID: "support"
      KAFKA_SERVER: "broker_support:9092"