spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/support}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate